### ISSUE TITLE
Tutorial doesn't compile

### ISSUE THREAD

**Issue by Karsten1987** [snapcraft-docs/ros2-talker-listener#2]
I am basically following the [online tutorial](https://snapcraft.io/first-snap/ros2/linux/package), which leverages the `snapcraft.yaml` provided in this repo, but unfortunately it fails with the following error message:

```
ERROR: no rosdep rule for 'std_msgs'
Package 'std_msgs' isn't a valid system dependency. Did you forget to add it to colcon-packages? If not, add the Ubuntu package containing it to stage-packages until you can get it into the rosdep database.
```

Similarly, when updating the code base to eloquent, I get colcon error messages. 

Is there a recommended way of debugging this? I am fairly unfamiliar with snaps in general and would also like to see where's the right place to debug the colcon plugin.

any hints are appreciated on how to proceed further on this issue.

**Comment by kyrofa** [comment]
Hey @Karsten1987. The tutorial uses Crystal, which is EOL and snapcraft doesn't tell rosdep to check EOL distros (it should, this [is a bug](https://github.com/snapcore/snapcraft/pull/2965)). I'm trying to get the tutorial updated, but in the meantime try using Dashing or Eloquent.

**Comment by Karsten1987** [comment]
Thanks for your reply. As mentioned above, when updating the `snapcraft.yaml` to eloquent, I get the following error when reaching the actual colcon command:

```
colcon build --merge-install --build-base /root/parts/ros-demos/build --base-paths /root/parts/ros-demos/src/demo_nodes_cpp --install-base /root/parts/ros-demos/install/opt/ros/snap --parallel-workers=2 --cmake-args -DCMAKE_BUILD_TYPE=Release
Starting >>> demo_nodes_cpp
--- stderr: demo_nodes_cpp                            
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libpcre.so', needed by 'listener'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libpcre.so', needed by 'listener_serialized_message'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/listener.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/listener_serialized_message.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< demo_nodes_cpp     [ Exited with code 2 ]

Summary: 0 packages finished [7.69s]
  1 package failed: demo_nodes_cpp
  1 package had stderr output: demo_nodes_cpp
Failed to run 'colcon build --merge-install --build-base /root/parts/ros-demos/build --base-paths /root/parts/ros-demos/src/demo_nodes_cpp --install-base /root/parts/ros-demos/install/opt/ros/snap --parallel-workers=2 --cmake-args -DCMAKE_BUILD_TYPE=Release' for 'ros-demos': Exited with code 2.
Verify that the part is using the correct parameters and try again.
```

I was wondering what's the recommended steps to debug this.

**Comment by kyrofa** [comment]
Huh, you're right. I'm honestly not sure what's going on with Eloquent; it's looking in the wrong place for that lib (which is in `parts/ros-demos/install`). I'm looking into it now. Note that it works fine in Dashing:

```
name: test-ros2-talker-listener-kyrofa
version: '0.1'
summary: ROS2 Talker/Listener Example
description: |
  This example launches a ROS2 talker and listener.
confinement: devmode
base: core18
parts:
  ros-demos:
    plugin: colcon
    source: https://github.com/ros2/demos.git
    source-branch: dashing
    colcon-rosdistro: dashing
    colcon-source-space: demo_nodes_cpp
    build-packages: [make, gcc, g++]
    stage-packages: [ros-dashing-ros2launch]
apps:
  run:
    command: opt/ros/dashing/bin/ros2 launch demo_nodes_cpp talker_listener.launch.py
```
